# development configuration
server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_app
    username: root
    password:

  # it will automatically update the table of the database instead of creating or drop instantly
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

security:
  jwt:
    secret: ${JWT_SECRET}
    issuer: ${JWT_ISSUER}
    access-ttl-second: ${JWT_ACCESS_TTL_SECOND}
    refresh-ttl-second: ${JWT_REFRESH_TTL_SECOND}
    refresh-token-cookie:
      name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
      secure: ${JWT_REFRESH_COOKIE_SECURE:true}
      http-only: ${JWT_REFRESH_COOKIE_HTTP_ONLY:true}
      same-site: ${JWT_REFRESH_COOKIE_SAME_SITE:lax}
      domain: ${JWT_COOKIE_DOMAIN:localhost}